Added AttachablesModule
Recursyve/nestjs-quickbooks pull request #22
Opened 2022-09-27 23:06 UTC by JulienDuf

2022-09-28 04:14 UTC, Gabrielbdry requested changes

2022-09-28 04:14 UTC, Gabrielbdry commented on lib/modules/attachables/services/attachables.service.ts
> +
```suggestion
```

2022-09-28 04:14 UTC, Gabrielbdry commented on lib/modules/attachables/services/attachables.service.ts
> +
```suggestion
```

2022-09-28 04:14 UTC, Gabrielbdry commented on lib/modules/attachables/dto/attachables.dto.ts
> +    AttachableRef?: QuickBooksAttachableRefDto[];
Il manque le FileName?

2022-09-28 04:15 UTC, Gabrielbdry requested changes

2022-09-28 04:15 UTC, Gabrielbdry commented on lib/modules/attachables/dto/attachables.dto.ts
> +
Le full update de l'api explorer a l'air d'avoir beaucoup plus de champs

2022-09-28 12:47 UTC, Jtplouffe commented on lib/modules/attachables/services/attachables.service.ts
> +                    "Content-Length": data.getLengthSync()
Tu va geler le main thread avec ça, faudrait utilisé la méthode async, qui est un callback https://github.com/form-data/form-data#integer-getlength-function-callback-

2022-09-28 15:33 UTC, JulienDuf commented on lib/modules/attachables/services/attachables.service.ts
> +                    "Content-Length": data.getLengthSync()
Ça va être un peu difficile d'utiliser une callback pour aller chercher cette information là

2022-09-28 15:59 UTC, Gabrielbdry approved these changes

2022-09-29 11:35 UTC, Jtplouffe approved these changes

2022-09-29 13:34 UTC, merged